<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet exclude-result-prefixes="xalan xsi" version="1.0"
    xmlns:xalan="http://xml.apache.org/xslt"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
    <!--This file has been generated by Enovacom Suite V2 Mapper v1.2.6-->
    <xsl:output encoding="UTF-8" indent="yes" method="xml"/>
    <xsl:template match="/resultSet">
        <xsl:variable name="rootNode" select="."/>
        <xsl:element name="root">
            <xsl:for-each select="$rootNode/row">
                <xsl:variable name="var1_row" select="."/>
                <xsl:element name="PID">
                    <xsl:for-each select="$var1_row/PatientID">
                        <xsl:variable name="var2_PatientID" select="."/>
                        <xsl:element name="PID.3.1">
                            <xsl:value-of select="$var2_PatientID"/>
                        </xsl:element>
                    </xsl:for-each>
                    <xsl:for-each select="$var1_row/Surname">
                        <xsl:variable name="var3_Surname" select="."/>
                        <xsl:element name="PID.5.1">
                            <xsl:value-of select="$var3_Surname"/>
                        </xsl:element>
                    </xsl:for-each>
                    <xsl:for-each select="$var1_row/GivenName">
                        <xsl:variable name="var4_GivenName" select="."/>
                        <xsl:element name="PID.5.2">
                            <xsl:value-of select="$var4_GivenName"/>
                        </xsl:element>
                    </xsl:for-each>
                    <xsl:for-each select="$var1_row/Title">
                        <xsl:variable name="var5_Title" select="."/>
                        <xsl:element name="PID.5.3">
                            <xsl:value-of select="$var5_Title"/>
                        </xsl:element>
                    </xsl:for-each>
                </xsl:element>
            </xsl:for-each>
        </xsl:element>
    </xsl:template>
</xsl:stylesheet>
